### ISSUE TITLE
ErrorDocument 401 doesn't redirect specified url

### ISSUE THREAD

**Issue by Kojiro-Goto** [ZenProjects/Apache-Authmemcookie-Module#20]
URL cannot be set as 401 errordocument.

> ErrorDocument 401 "/gestionuser/login.php"

This is ignored.

Do you have any alternative solution?

**Comment by mcarbonneaux** [comment]
Why you cannot ? more context needed to understand your problem

The authentification module dont do redirect, they return 401 error, is why you must customise 401 error page with apache errordocument.

Errordocument is like alias and dont do redirect and can use only local page served by apache.

https://httpd.apache.org/docs/2.4/en/custom-error.html

To use Dynamique page like PHP page your apache must be configured to serve PHP page with PHP.

Rise the log level of Apache understand why they do not do what they suposed to do.

**Comment by Kojiro-Goto** [comment]
@mcarbonneaux 
Thank you for your comments.

I did a lot of things to investigate my problem.

1. PHP configuration is correct. If 401 set as "/redirect.php" and this php just sent back 302 header,  then works fine.
2. Static html file is also works fine.

Only when I use simplesaml php auth memcookie module, it doesn't work expectedly.
* simplesaml php auth memcooie module is here https://github.com/simplesamlphp/simplesamlphp-module-memcookie

And I found the issue that apache set the value of REQUEST_URI env original url.

When the location "/protected/" set for Auth Memcookie and set the ErrorDocument 401 in this location like below.
<Location /protected>
     Auth_memCookie...
     ErrorDocument 401 /redirect.php
</Location>

When apache access to the redirect.php the value of REQUEST_URI is "/protected".
Simplesamlphp doesn't work if REQUEST_URI is not the same as the path set as 401.(like simplesaml/module.php/memcookie/auth.php)

The issue is related to simplesamlphp or simplesaml memcookie module so you can close this issue.
