### ISSUE TITLE
group authentication not working

### ISSUE THREAD

**Issue by gavinjackson** [ZenProjects/Apache-Authmemcookie-Module#5]
Hello,

Thanks for writing this apache module - hopefully this will allow us to use simplesamlphp as an SP for our mod_wsgi python webapps! I have authentication working ok, but am struggling with authorization.

Just trying to get group authentication working. Here is my config:
<Location /ssp>
        Auth_memCookie_SessionTableSize "40"
        Auth_memCookie_Authoritative on
        Auth_memCookie_GroupAuthoritative on
        Require valid-user
        Require group blah
</Location>

When starting up apache, I see the following error message:
Nov 12 10:23:23 webapps-dr apache2[20440]: \* The apache2 configtest failed.
Nov 12 10:23:23 webapps-dr apache2[20440]: Output of config test was:
Nov 12 10:23:23 webapps-dr apache2[20440]: AH00526: Syntax error on line 49 of /etc/apache2/conf-enabled/auth_memcookie.conf:
Nov 12 10:23:23 webapps-dr apache2[20440]: Unknown Authz provider: group
Nov 12 10:23:23 webapps-dr apache2[20440]: Action 'configtest' failed.

I am running apache2 version 2.4.10-9ubuntu1.1 on Ubuntu 15.04 (vivid) with patched (inline bug) version of libmemcache 1.4.0rc2.

Any thoughts?

**Comment by mcarbonneaux** [comment]
i've you loaded mod_authz_groupefile and/or mod_authz_user ?
because the actual 2.4 implementation of AuthMemCookie overider apache Require directive to mimique 2.2 implementation...

**Comment by mcarbonneaux** [comment]
Group are not implemented in first 2.4 try... Now they are implemented correctly accordingly to the new apache 2.3/2.4 authorization system in 2.0 of my module. Read the documentation for configuration details (they use Require mcac-group in place of Require Group) .
