### ISSUE TITLE
Apache 2.4 partial support ?

### ISSUE THREAD

**Issue by benrubson** [ZenProjects/Apache-Authmemcookie-Module#7]
Hello,

In the changelog you talk about `Apache 2.4 partial support`.
Is there still something missing to have a full / clean support of Apache 2.4 ?

Thank you very much !

Ben

**Comment by mcarbonneaux** [comment]
apache 2.4 as completely rewrite the authentification & authorisation mecanisme vs apache 2.2.
https://httpd.apache.org/docs/2.4/en/howto/auth.html

Authentication and Authorization are now separated.

they must remplement my module in that new way.

they actualy simulate authentification mecanisme with adding the old "Require" configuration directive...

https://github.com/ZenProjects/Apache-Authmemcookie-Module/commit/d4f206afc35db3d677aab72d26c0128afaddb95a

**Comment by mcarbonneaux** [comment]
i've released the full / clean support of the apache 2.4 the v2.0 of my module !

**Comment by benrubson** [comment]
Excellent, thank you very much Mathieu 👍
