### ISSUE TITLE
Thread safe ?

### ISSUE THREAD

**Issue by benrubson** [ZenProjects/Apache-Authmemcookie-Module#8]
Hello,

Is Authmemcookie module thread safe ?
https://httpd.apache.org/docs/2.4/developer/thread_safety.html

Thank you very much !

Ben

**Comment by mcarbonneaux** [comment]
my code are normaly thread safe because use massively apr library and apache memory pool, but i'm not sure for libmemcache...

but i initialise libmemcache session, use and close in the same function... i think is prety thread safe in that way...

**Comment by mcarbonneaux** [comment]
now they use libmemcached that are thread safe....

**Comment by benrubson** [comment]
Thank you Mathieu 👍
